### PR TITLE
Landing page - split into separate components and sections

### PR DESCRIPTION
**Pull request by ehud91**

### CODE REVIEW

**Review by seladb — APPROVED** [review]

**Comment by seladb** [comment]
With this PR the heading is now missing...

image

**Comment by ehud91** [comment]
Are you sure?
It seems weird, there are no errors as I see it in my repo and local repo.

‫בתאריך יום ד׳, 12 בינו׳ 2022 ב-9:22 מאת ‪seladb‬‏ <‪
***@***.***‬‏>:‬

**Comment by seladb** [comment]
There are no errors, it just doesn't show the heading (I attached a screenshot to the previous comment)

**Comment by ehud91** [comment]
I will check this issue in my repo and i'll fix it

**Pull request merged**
